### ISSUE TITLE
Crashing Bug: Unknown SCSI command 0x1b

### ISSUE THREAD

**Issue by dvogel** [lenticularis39/axpbox#85] opened 2022-07-22 23:38 UTC
Thanks for this excellent program. I've been using it to get OpenVMS 8.2 up and running. It works great for the most part. However I did just see it crash immediately after trying to logout.

From my telnet session:
```
            *EXIT*
   49       $
*WRITE LOGIN.COM
SYS$SYSROOT:[SYSMGR]LOGIN.COM;1 51 lines
*QUIT

$ logout
Connection closed by foreign host.L-2022 18:33:59.41
```

From my terminal where axpbox was running:
```
./axpbox run
sys0(tsunami): $Id: System.cpp,v 1.79 2008/06/12 07:29:44 iamcamiel Exp $
flash: 2097156 bytes restored.
%FLS-I-RESTST: Flash state restored from rom/flash.rom
sys0(tsunami): $Id: Flash.cpp,v 1.19 2008/03/24 22:11:50 iamcamiel Exp $
pci0.15(ali_ide).disk0.0(file): Mounted file disk0.img, 10485760 512-byte blocks, 16384/16/40.
pci0.2(sym53c810).disk0.1(file): Mounted file ../FREEWARE80_1.ISO, 208371 2048-byte blocks, 69457/3/1.
pci0.2(sym53c810).disk0.2(file): Mounted file ../FREEWARE80_2.ISO, 198647 2048-byte blocks, 198647/1/1.
pci0.2(sym53c810).disk0.3(file): Mounted file ../FREEWARE80_3.ISO, 198920 2048-byte blocks, 4973/10/4.
pci0.2(sym53c810).disk0.4(file): Mounted file ../FREEWARE10.ISO, 219931 2048-byte blocks, 219931/1/1.
dma: $Id: DMA.cpp,v 1.9 2008/04/29 09:24:52 iamcamiel Exp $
pci0.19(ali_usb): $Id: AliM1543C_usb.cpp,v 1.6 2008/03/14 15:30:50 iamcamiel Exp $
dpr: 16384 bytes restored.
%DPR-I-RESTST: DPR state restored from rom/dpr.rom
sys0(tsunami): $Id: DPR.cpp,v 1.23 2008/06/12 07:29:44 iamcamiel Exp $
cpu0(ev68cb)(0): $Id: AlphaCPU.cpp,v 1.82 2009/03/16 01:33:27 iamcamiel Exp $
serial0(serial): Waiting for connection on port 21264.
serial0(serial): $Id: Serial.cpp,v 1.51 2008/06/03 09:07:56 iamcamiel Exp $
%IDE-I-INIT: New IDE emulator initialized.
pci0.2(sym53c810): $Id: Sym53C810.cpp,v 1.14 2008/05/31 15:47:13 iamcamiel Exp $
pci0.4(dec21143): MAC set to 9C-75-14-77-29-F6
pci0.4(dec21143): $Id: DEC21143.cpp,v 1.36 2008/05/31 15:47:09 iamcamiel Exp $
pci0.7(ali): $Id: AliM1543C.cpp,v 1.66 2008/05/31 15:47:07 iamcamiel Exp $
kbc: $Id: Keyboard.cpp,v 1.10 2008/05/31 15:47:09 iamcamiel Exp $
%SYS-I-READROM: Reading decompressed ROM image from rom/decompressed.rom.
%SYM-I-PATCHROM: Patching ROM for speed.
%SYS-I-ROMLOADED: ROM Image loaded successfully!
dpr: 16384 bytes restored.
%DPR-I-RESTST: DPR state restored from rom/dpr.rom
sys0(tsunami): $Id: DPR.cpp,v 1.23 2008/06/12 07:29:44 iamcamiel Exp $
Start threads: cpu0 srl0 ide0 ide1 sym nic ali kbd
*** CPU0 *** STARTING ***
Arbitration 0000000000010000 from CPU 0 (@13e39)... won  0000000800010000
Arbitration clear from CPU 0 (@13f55).
Arbitration 0000000000010000 from CPU 0 (@13351)... won  0000000800010000
Arbitration clear from CPU 0 (@133b9).
Arbitration 0000000000010000 from CPU 0 (@13351)... won  0000000800010000
Arbitration clear from CPU 0 (@133b9).
Arbitration 0000000000010000 from CPU 0 (@13351)... won  0000000800010000
Arbitration clear from CPU 0 (@133b9).
*** IP interrupt set for CPU 0 from CPU 0(@ 110d5)
*** IP interrupt cleared for CPU 0 from CPU 0(@ 1a140c).
Exception in SYM thread: Not implemented: pci0.2(sym53c810).disk0.4(file): Unknown SCSI command 0x1b.
: /home/dvogel/tmp/VMS/axpbox/src/Disk.cpp, line 1399.
Emulator Failure: Threading error: SYM thread has died: /home/dvogel/tmp/VMS/axpbox/src/Sym53C810.cpp, line 1455
Stop threads: cpu0 srl0 ide0 ide1 sym nic ali kbd
Freeing memory in use by system...
pci0.15(ali_ide).disk0.0(file): Closing file.
```

My es40.cfg:
```
cat es40.cfg 
sys0 = tsunami
{
  memory.bits = 28;
  rom.srm = "rom/cl67srmrom.exe";
  rom.decompressed = "rom/decompressed.rom";
  rom.flash = "rom/flash.rom";
  rom.dpr = "rom/dpr.rom";

  cpu0 = ev68cb
  {
    speed = 800M;
    icache = false;
    skip_memtest_hack = true;
  }

  serial0 = serial
  {
    port = 21264;
    action = "";
  }

  pci0.15 = ali_ide
  {
    disk0.0 = file
    {
      file = "disk0.img";
      cdrom = false;
      read_only = false;
      model_number = "";
      rev_number = "";
      serial_number = "";
    }
  }

	pci0.2 = sym53c810
	{
		disk0.1 = file
		{
			file = "../FREEWARE80_1.ISO";
			// file = "../ALPHA0842L1.ISO";
			cdrom = true;
			read_only = true;
		}
		disk0.2 = file
		{
			file = "../FREEWARE80_2.ISO";
			// file = "../AVMS842L2LP1/AVMS842L2LP1.ISO";
			cdrom = true;
			read_only = true;
		}
		disk0.3 = file
		{
			file = "../FREEWARE80_3.ISO";
			// file = "../AVMS842L2LP2/AVMS842L2LP2.ISO";
			cdrom = true;
			read_only = true;
		}
		disk0.4 = file
		{
			file = "../FREEWARE10.ISO";
			cdrom = true;
			read_only = true;
		}
	}

	pci0.4 = dec21143 
	{
		adapter = "enp5s0";
		mac = "9C-75-14-77-29-F6";
	}

  pci0.7 = ali
  {
      mouse.enabled = false;
      vga_console = false;
  }

  pci0.19 = ali_usb
  {
  }
}
```

**Comment by lenticularis39** [comment] 2023-05-08 15:28
Looks like a duplicate of #36.

**Closed by lenticularis39** 2023-05-08 15:28 UTC
